#!/bin/sh

./run-BlackBox <<DATA
DevCompiler.CompileThis ObxHello0 ObxPi
ObxHello0.Do
ObxPi.WritePi(1000)

ConsCompiler.Compile('Obx/Mod', 'Hello0.odc')
ConsCompiler.Compile('Obx/Mod', 'Pi.odc')

ConsCompiler.Compile('', 'HostFonts.txt')

DevElfLinker.LinkDll libBB1.so := Kernel+ Kernel_so_init# Files HostFiles StdLoader
DATA

./run-BlackBox <<DATA
DevCompiler.CompileThis DevLinker
DevLinker.LinkDll BlackBox.exe := Kernel$+ Files HostFiles StdLoader
DATA

### test PackedFiles:

echo XXXXXXXXXXX > packedfiles
./run-BlackBox <<DATA
DevElfLinker.LinkDll libBB1.so := Kernel+ Files HostFiles HostPackedFiles StdLoader
DevPacker.PackThis libBB1.so := Code/Init.ocf ~
DevPacker.PackThis packedfiles := Code/Init.ocf ~
DATA

mv Code/Init.ocf Code/Init.ocf.bak
env BB_PACKED_NAME=libBB1.so ./loader ./libBB1.so <<DATA
Log.String('PackedFiles works!')
Log.Ln
DATA
env BB_PACKED_NAME=packedfiles ./loader ./libBB1.so <<DATA
Log.String('PackedFiles works!')
Log.Ln
DATA
mv Code/Init.ocf.bak Code/Init.ocf
rm -f packedfiles

### end of test PackedFiles
