#!/bin/sh

./run-dev0 <<DATA
ConsCompiler.Compile('Lin/Mod', 'Dl.txt')
ConsCompiler.Compile('Lin/Mod', 'Libc.txt')
ConsCompiler.Compile('Lin/Mod', 'Iconv.txt')
DevCompiler.CompileThis Kernel

DevCompiler.CompileThis Files Console Math Strings Meta Dialog

DevCompiler.CompileThis HostLang HostFiles HostConsole

DevCompiler.CompileThis Stores Converters Dates Integers Sequencers Services Log SMath

DevCompiler.CompileThis Fonts Ports Printers Models Views Printing Mechanisms Controllers Properties Containers Documents Windows

DevCompiler.CompileThis TextModels TextMappers TextRulers TextSetters TextViews TextControllers TextCmds

DevCompiler.CompileThis In

DevCompiler.CompileThis StdDialog StdApi StdCFrames Controls StdCmds StdLogos StdScrollers StdViewSizer

DevCompiler.CompileThis StdClocks StdCoder StdFolds StdDebug StdStamps StdETHConv StdHeaders StdLinks

DevCompiler.CompileThis StdLoader
DevCompiler.CompileThis Kernel_so_init

# before StdLog
ConsCompiler.Compile('Host/Mod', 'Dialog.txt')

DevCompiler.CompileThis StdLog
DevCompiler.CompileThis Out
ConsCompiler.Compile('Cons/Mod', 'Log.txt')

DevCompiler.CompileThis DevMarkers DevCommanders DevSelectors DevCPM DevCPT DevCPH DevCPB DevCPE DevCPS DevCPP DevCPL486 DevCPC486 DevCPV486 DevCompiler DevElfLinker16 DevLinker
DevCompiler.CompileThis ConsCompiler

DevCompiler.CompileThis StdInterpreter

### BlackBox

ConsCompiler.Compile('Host/Mod', 'Fonts.txt')
ConsCompiler.Compile('Host/Mod', 'Windows.txt')
DevCompiler.CompileThis HostDates
DevCompiler.CompileThis HostTextConv

ConsCompiler.Compile('Cons/Mod', 'Interp.txt')

ConsCompiler.Compile('System/Mod', 'Init.txt')
DevCompiler.CompileThis Config

DevElfLinker.LinkDll libBB.so := Kernel+ Files HostFiles StdLoader

DevCompiler.CompileThis HostPackedFiles DevPacker

DevCompiler.CompileThis CommStreams
ConsCompiler.Compile('Lin/Mod', 'Termios.txt')
ConsCompiler.Compile('Lin/Mod', 'Ioctl.txt')
ConsCompiler.Compile('Lin/Mod', 'Net.txt')
DevCompiler.CompileThis CommV24 CommTCP

DevCompiler.CompileThis XhtmlEntitySets XhtmlWriters XhtmlStdFileWriters XhtmlTextTableMarkers XhtmlExporter

DevCompiler.CompileThis ObxHello0 ObxPi ObxRandom ObxTrap
DATA
