#!/bin/sh

# ulimit -s 32000

rn=`readlink -f "${0}"`
d=`dirname "${rn}"`

exe="BlackBox-dl"
appName=${exe}

# export LD_DEBUG=all
env LD_LIBRARY_PATH="${d}" CMDLINE="${d}/${appName} `echo ${@}`" "${d}"/${exe}
