#!/bin/sh

none() {
	if [ -e System/Mod/Kernel.odc -a ! -h System/Mod/Kernel.odc ]; then
		echo Kernel.odc modified
		exit 1
	fi

	rm -rf \
		System/Mod/Kernel.odc System/Mod/Kernel.txt System/Code/Kernel.ocf System/Sym/Kernel.osf \
		Code/Kernel.ocf Sym/Kernel.osf \
		Host Win Lin BlackBox blackbox.exe BlackBox.exe *.so dev0
}

obsd() {
	ln -s ../../OpenBSD/System/Mod/Kernel.odc System/Mod/Kernel.odc
	ln -s ../../OpenBSD/System/Mod/Kernel.txt System/Mod/Kernel.txt
	ln -s OpenBSD/Lin
	ln -s OpenBSD/Host
	ln -s OpenBSD/libBB.so
	ln -s OpenBSD/libBB0.so
	ln -s OpenBSD/BlackBox
	ln -s OpenBSD/dev0
	ln -s OpenBSD/libdlobsdwrap.so
}

lin() {
	ln -s ../../Linux/System/Mod/Kernel.odc System/Mod/Kernel.odc
	ln -s ../../Linux/System/Mod/Kernel.txt System/Mod/Kernel.txt
	ln -s Linux/Lin
	ln -s Linux/Host
	ln -s Linux/libBB.so
	ln -s Linux/libBB0.so
	ln -s Linux/BlackBox
	ln -s Linux/dev0
}

case $1 in
none)
	none
	;;
OpenBSD)
	none && obsd
	;;
Linux)
	none && lin
	;;
*)
	echo "usage: `basename $0` ( none | OpenBSD | Linux )"
	;;
esac
