#!/bin/sh

./run-BlackBox <<DATA
DevCompiler.CompileThis ObxHello0 ObxPi
ObxHello0.Do
ObxPi.WritePi(1000)

ConsCompiler.Compile('Obx/Mod', 'Hello0.odc')
ConsCompiler.Compile('Obx/Mod', 'Pi.odc')

ConsCompiler.Compile('', 'HostFonts.txt')

DevElfLinker.LinkDll libBB.so := Kernel+ Kernel_so_init# Files HostFiles StdLoader
DATA

./run-BlackBox <<DATA
DevCompiler.CompileThis DevLinker
DevLinker.LinkDll BlackBox.exe := Kernel$+ Files HostFiles StdLoader
DATA
