#!/bin/sh

./run-BlackBox <<DATA
DevCompiler.CompileThis ObxHello0 ObxPi
ObxHello0.Do
ObxPi.WritePi(1000)

ConsCompiler.Compile('Obx/Mod', 'Hello0.odc')
ConsCompiler.Compile('Obx/Mod', 'Pi.odc')

DevElfLinker.LinkDll libBB.so := Kernel+ Files HostFiles StdLoader
DATA
